import { VoiceProfile } from '../types/voice';

export const PRESET_VOICES: VoiceProfile[] = [
  {
    id: 'preset-david',
    name: 'Sir David (Nature Documentarian)',
    createdAt: 1711600000000,
    sampleDuration: 18,
    sampleTranscription:
      'Here, in the vast wilderness of the Serengeti, life moves in delicate harmony. Every creature, no matter how small, plays an indispensable part.',
    gender: 'male',
    ageGroup: 'mature',
    accent: 'British RP (Received Pronunciation)',
    emotionalTone: 'Awe-inspiring, gentle, authoritative, whisper-adjacent wonder',
    anchorVoice: 'Charon',
    styleDirective:
      'Elderly British gentleman, nature documentary narrator. Gentle, hushed wonder, calm breathy pauses, deliberate cadence, warm baritone resonance, rich storytelling intonation.',
    metrics: {
      f0Hz: 110,
      pitchMinHz: 85,
      pitchMaxHz: 160,
      vocalRegister: 'Baritone',
      warmth: 92,
      breathiness: 45,
      raspiness: 38,
      resonance: 85,
      clarity: 90,
      wordsPerMinute: 115,
      dynamicRange: 'Wide theatrical dynamic range with soft delicate whispers',
    },
    dsp: {
      pitchShiftSemi: -2,
      eqBassGain: 3.0,
      eqMidGain: -0.5,
      eqTrebleGain: 1.5,
      reverbAmount: 0.14,
      tempoRatio: 0.9,
    },
    sampleSuggestions: [
      'Beneath the canopy of the rainforest, twilight descends, bringing to life an unseen universe.',
      'For millions of years, the ocean currents have sculpted our continents and sheltered mysterious wonders.',
      'Witness the miraculous journey of the monarch butterfly, crossing thousands of miles against all odds.',
    ],
    isPreset: true,
  },
  {
    id: 'preset-elena',
    name: 'Elena (Warm Audiobook Storyteller)',
    createdAt: 1711600001000,
    sampleDuration: 14,
    sampleTranscription:
      'She stood at the edge of the ancient library, where dusty shafts of morning light revealed books that had waited centuries to be read.',
    gender: 'female',
    ageGroup: 'adult',
    accent: 'Mid-Atlantic / Transatlantic Clear',
    emotionalTone: 'Warm, captivating, empathetic, melodic storytelling',
    anchorVoice: 'Kore',
    styleDirective:
      'Warm feminine storyteller, rich melodic cadence, articulate enunciation, soothing chest warmth, gentle pauses at narrative transitions, inviting and cozy presence.',
    metrics: {
      f0Hz: 210,
      pitchMinHz: 160,
      pitchMaxHz: 280,
      vocalRegister: 'Mezzo-Soprano',
      warmth: 88,
      breathiness: 28,
      raspiness: 8,
      resonance: 80,
      clarity: 95,
      wordsPerMinute: 135,
      dynamicRange: 'Expressive lyrical narrative contour',
    },
    dsp: {
      pitchShiftSemi: 0,
      eqBassGain: 1.5,
      eqMidGain: 1.0,
      eqTrebleGain: 2.0,
      reverbAmount: 0.1,
      tempoRatio: 1.0,
    },
    sampleSuggestions: [
      'The key felt cold in her palm, but the brass door seemed to hum with silent anticipation.',
      'Once upon a quiet winter evening, when snow muffled the footsteps of the entire town, a lantern flickered.',
      'Close your eyes and breathe deeply. You are surrounded by stillness, peace, and endless starry skies.',
    ],
    isPreset: true,
  },
  {
    id: 'preset-marcus',
    name: 'Marcus (Late-Night FM Radio)',
    createdAt: 1711600002000,
    sampleDuration: 15,
    sampleTranscription:
      'You are tuned in to the midnight groove. Pour yourself a hot cup, settle into your favorite chair, and let the smooth frequencies carry you.',
    gender: 'male',
    ageGroup: 'middle-aged',
    accent: 'Urban American Deep Resonance',
    emotionalTone: 'Velvety, intimate, relaxed, deep baritone',
    anchorVoice: 'Fenrir',
    styleDirective:
      'Ultra-deep baritone late night radio DJ. Velvety proximity effect, slow confident rhythm, relaxed vocal fry on sentence endings, smooth conversational swagger.',
    metrics: {
      f0Hz: 92,
      pitchMinHz: 75,
      pitchMaxHz: 130,
      vocalRegister: 'Bass-Baritone',
      warmth: 96,
      breathiness: 20,
      raspiness: 30,
      resonance: 98,
      clarity: 88,
      wordsPerMinute: 120,
      dynamicRange: 'Compressed warm intimate broadcast dynamic',
    },
    dsp: {
      pitchShiftSemi: -3,
      eqBassGain: 5.0,
      eqMidGain: -1.0,
      eqTrebleGain: 2.0,
      reverbAmount: 0.08,
      tempoRatio: 0.95,
    },
    sampleSuggestions: [
      'Midnight has arrived, and whatever kept your mind racing today, leave it at the doorstep.',
      'Coming up next is a classic soul track that will make the clock on the wall freeze in time.',
      'Thank you for riding with me through the night. Stay safe, stay cool, and keep the music loud.',
    ],
    isPreset: true,
  },
  {
    id: 'preset-maya',
    name: 'Maya (Silicon Valley Tech Founder)',
    createdAt: 1711600003000,
    sampleDuration: 16,
    sampleTranscription:
      'What we are unveiling today isn’t just an incremental feature. It completely redefines the boundary between human creativity and artificial intelligence.',
    gender: 'female',
    ageGroup: 'young adult',
    accent: 'California / Tech Standard American',
    emotionalTone: 'Visionary, sharp, confident, enthusiastic, crisp',
    anchorVoice: 'Zephyr',
    styleDirective:
      'Sharp, energetic Silicon Valley founder. Crisp enunciation, forward-moving cadence, bright vocal presence, confident upward inflections on key insights, dynamic keynote energy.',
    metrics: {
      f0Hz: 225,
      pitchMinHz: 175,
      pitchMaxHz: 310,
      vocalRegister: 'Alto',
      warmth: 72,
      breathiness: 15,
      raspiness: 10,
      resonance: 82,
      clarity: 98,
      wordsPerMinute: 155,
      dynamicRange: 'Punchy keynote dynamic with staccato emphasis',
    },
    dsp: {
      pitchShiftSemi: 1,
      eqBassGain: 0.5,
      eqMidGain: 2.0,
      eqTrebleGain: 3.0,
      reverbAmount: 0.06,
      tempoRatio: 1.05,
    },
    sampleSuggestions: [
      'Today, we are launching our next generation model, 10x faster with half the memory footprint.',
      'When we started this company three years ago, people told us real-time voice cloning in the browser was impossible.',
      'The future belongs to builders who dare to rethink the entire stack from the ground up.',
    ],
    isPreset: true,
  },
  {
    id: 'preset-alex',
    name: 'Alex (High-Energy YouTuber / Streamer)',
    createdAt: 1711600004000,
    sampleDuration: 12,
    sampleTranscription:
      'Yo what is up everybody! Drop a like right now because what I’m about to show you is absolutely mind-blowing!',
    gender: 'male',
    ageGroup: 'youth',
    accent: 'Fast Casual American',
    emotionalTone: 'Hyper-energetic, playful, humorous, fast-paced',
    anchorVoice: 'Puck',
    styleDirective:
      'High-energy internet creator. Rapid-fire tempo, expressive pitch jumps, playful chuckles, enthusiastic vocal punches, casual modern slang delivery.',
    metrics: {
      f0Hz: 170,
      pitchMinHz: 120,
      pitchMaxHz: 290,
      vocalRegister: 'Tenor',
      warmth: 65,
      breathiness: 12,
      raspiness: 18,
      resonance: 74,
      clarity: 92,
      wordsPerMinute: 175,
      dynamicRange: 'Explosive high-energy dynamic peaks',
    },
    dsp: {
      pitchShiftSemi: 1,
      eqBassGain: 1.0,
      eqMidGain: 1.5,
      eqTrebleGain: 2.5,
      reverbAmount: 0.05,
      tempoRatio: 1.15,
    },
    sampleSuggestions: [
      'Smash that subscribe button! We are literally giving away the entire setup in today’s challenge!',
      'Wait, did you see that?! No way that just happened on the first attempt! <laugh>',
      'Let me know in the comments below: would you rather have supersonic flight or unlimited AI compute?',
    ],
    isPreset: true,
  },
];
